spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  docker:
    compose:
      lifecycle-management: start_only
      file: server/compose.yaml
  sql:
    init:
      mode: always