spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: postgres
    password: bestuser
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create